### ISSUE TITLE
Testnet IoP Wallet has a Pink Logo on the Windows Taskbar but a Purple Icon with the Volume/Wifi Icons

### ISSUE THREAD

**Issue by kayabaNerve** [Internet-of-People/iop-core#10]
We have two different graphics, one loading on the Taskbar, one on the Icon tray. The purple on is much better IMO...

I'm using IoP Node 6.1.0 on Windows 10.

**Comment by Anfauglith** [comment]
I fixed the logo, it will be included in next release... this is low priority to the extreme :)

**Comment by Anfauglith** [comment]
Its fixed in version 6.2.0
