### ISSUE TITLE
IoP-hd-v6.0.0bs-win64-setup-unsigned.exe does not install the way release notes suggest

### ISSUE THREAD

**Issue by anastrophe** [Internet-of-People/iop-core#2]
### Describe the issue
wallet release notes state:
"The new client is 100% compatible with the old consensus, but to facilitate the transition and prevent data loss, the new client is called IoP-HD. The default location of the data directory has been changed so no conflicts occur. The directories are ~/Application Support/IoP-HD on macOS, %APPDATA%\IoP-HD on Windows, "

On running installer, client was installed in same location as previous releases - c:\Program Files\IoP rather than IoP-HD. Data directory was also not changed, installing new data files in %APPDATA%\Roaming\IoP, rather than as above (which I think meant to say %APPDATA%\Roaming\IoP-HD)
### Can you reliably reproduce the issue?
Don't know. Would rather not uninstall and reinstall.

#### If so, please list the steps to reproduce below:
1. run installer
2. accept all defaults (which included default of Program Files\IoP rather than IoP-HD
3.

### Expected behaviour
as above

### Actual behaviour
installed exactly as previous installers, my last used version being IoP-5.0.1-win64-setup-unsigned.exe

### What version of iop-core are you using?
IoP Core version v6.0.0.57-486b7da (64-bit)

### Machine specs:
- OS: Win 10 Pro
- CPU: i7-7700k no OC, 4.2ghz
- RAM: 32GB
- Disk size: 512GB
- Disk Type (HD/SDD): m.2 SSD

### Any extra information that might be useful in the debugging process.

Importantly: I incurred no problems at all. Client installed, ran fine, sees my previous transactions (even though it has yet to connect to peers, I'm 12 hours behind).

This is more of an informational report related to the release notes.

**Comment by anastrophe** [comment]
Just got back home, no connection to peers. I think I'll delete the data dir (yeah, i have a backup!) and reinstall.

**Comment by anastrophe** [comment]
I see now on reinstall that without the IoP dir in Roaming, One is presented with option for where to store the data. But that's still an error, since the Release notes said it would create a new directory not named IoP. That might need some clarification in the instructions.

Also, when it does present the option of where to save it - it says it'll download the whole blockchain 'back to 2009, at least 153GB'. I'm sure that's true for Bitcoin core, but it's not true for IoP!

**Comment by Anfauglith** [comment]
Hey anastrophe. 

Thanks for reporting the issue. Sorry that the instructions weren't clear.

I forgot to change the installation directory, as windows is the only platform with an installer. Sorry to everyone about that.

We'll also fix the UI bug.

**Comment by anastrophe** [comment]
Thank you kindly! I have another issue that's popped up, I'll open a new ticket for that.

**Comment by Anfauglith** [comment]
Fixed in the new beta
