### ISSUE TITLE
icon still bitcoin

### ISSUE THREAD

**Issue by mmatk** [Internet-of-People/iop-core#4]
![image](https://user-images.githubusercontent.com/487169/31666028-19446668-b34b-11e7-8d1d-38b12d5765c6.png)

**Comment by Anfauglith** [comment]
Oh, interesting. Thanks for the catch!

Am 17. Okt. 2017, 14:55 +0200 schrieb Markus <notifications@github.com>:

**Comment by Anfauglith** [comment]
Fixed!
